CREATE DATABASE agencia_viaje;
USE agencia_viaje;
CREATE TABLE usuarios (
ID INT AUTO_INCREMENT PRIMARY KEY,
NOMBRE_USUARIO VARCHAR (50) NOT NULL UNIQUE,
CONTRASENA VARCHAR (50) NOT NULL
);
INSERT INTO usuarios (NOMBRE_USUARIO, CONTRASENA) VALUES ('nicolas', password('1234QWERTY'));
